version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: udagram-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: udagram-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: