version: "3.8"
networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
services:
  reverseproxy:
    image: reverseproxy:latest
    networks:
     - backend
     - frontend
    env_file:
     - .env
  backend_user:
    image: udagram-api-user:latest
    networks:
     - backend
    env_file:
     - .env
  backend_feed:
    image: udagram-api-feed:latest
    networks:
     - backend
    env_file:
     - .env
  frontend:
    image: udagram-frontend:latest
    networks:
     - backend
     - frontend
    env_file:
     - .env
  db:
    image: postgres:16.1-alpine3.19
    networks:
     - backend
    env_file:
     - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
        
volumes:
  postgres-data: