version: "3.8"
networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
services:
  reverseproxy:
    image: reverseproxy:latest
    networks:
     - backend
     - frontend
    env_file:
     - .env
    ports:
     - "8080:8080"
  backend-user:
    image: udagram-api-user:latest
    networks:
     - backend
    env_file:
     - .env
    volumes:
     - ./.aws:/root/.aws
  backend-feed:
    image: udagram-api-feed:latest
    networks:
     - backend
    env_file:
     - .env
  frontend:
    image: udagram-frontend:latest
    networks:
     - frontend
    ports:
     - "8100:80"
    env_file:
     - .env
  db:
    image: postgres:16.1-alpine3.19
    networks:
     - backend
    env_file:
     - .env
    ports:
     - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
        
volumes:
  postgres-data: