version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy:latest
  backend-user:
    build:
      context: ./udagram-api-user
    image: udagram-api-user:latest
  backend-feed:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed:latest
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:latest
