apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user-deployment
  labels:
    app: backend-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
        - name: backend-user
          image: kovaj420/udagram-api-user:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: backend-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend-user-service
spec:
  selector:
    app: backend-user
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
