apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed-deployment
  labels:
    app: backend-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: kovaj420/udagram-api-feed:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: backend-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend-feed-service
spec:
  selector:
    app: backend-feed
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
